import {StyleSheet} from 'react-native';

const styles = (theme: any) => {
  return StyleSheet.create({
    primaryButton: {
      padding: 0,
      width: '100%',
      height: 45,
      flex: 1,
    },
    primaryButtonGradient: {
      height: 45,
      padding: 0,
      borderRadius: 4,
      justifyContent: 'center',
      width: '100%',
    },
    secondaryButtonStyle: {
      height: 45,
      backgroundColor: '#00316B',
      borderRadius: 4,
      padding: 9,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    secondaryButtonTextStyle: {
      textAlign: 'center',
      fontWeight: '500',
      fontSize: 14,
      padding: 0,
      lineHeight: 18,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryText,
    },
    btnTextStyle: {
      textAlign: 'center',
      fontWeight: '500',
      fontSize: 14,
      padding: 0,
      lineHeight: 20,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryText,
    },
    contestCardPage: {
      padding: 15,
      flex: 1,
    },
    contestCard: {
      borderRadius: 8,
      padding: 14,
      marginBottom: 15,
      width: '100%',
      borderColor: '#eeeeee',
      borderWidth: 1,
    },
    contestPrices: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    contestPrice: {
      backgroundColor: '#E3E3E3',
      height: 35,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 4,
      width: '48%',
      display: 'flex',
      marginBottom: 15,
    },
    contestPriceText: {
      fontFamily: theme.fonts.poppingsSemiBold,
      fontSize: 12,
      lineHeight: 24,
      fontWeight: '500',
    },
    contestHeader: {
      flexDirection: 'row',
      marginBottom: 15,
    },
    contestHImage: {
      backgroundColor: theme.colors.lightGrayBg,
      height: 65,
      width: 65,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
    },
    contestLogo: {
      height: 40,
      width: 40,
    },
    contestTitle: {
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '500',
      paddingHorizontal: 15,
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    contestStatus: {
      backgroundColor: '#D6EDBC',
      borderRadius: 4,
      height: 20,
      width: 50,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'flex-start',
      flexDirection: 'row',
    },
    contestStatusClosed: {
      backgroundColor: '#ff0000',
      borderRadius: 4,
      height: 20,
      width: 50,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'flex-start',
      flexDirection: 'row',
    },
    contestStatusUpcoming: {
      backgroundColor: '#e9e9e9',
      borderRadius: 4,
      height: 20,
      width: 80,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'flex-start',
      flexDirection: 'row',
    },
    contestStatusText: {
      fontSize: 12,
      lineHeight: 20,
      fontWeight: '500',
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    contestStatusTextWhite: {
      fontSize: 12,
      lineHeight: 20,
      fontWeight: '500',
      color: '#ffffff',
      fontFamily: theme.fonts.poppingsNormal,
    },
    dateCard: {
      flexDirection: 'row',
      marginBottom: 15,
    },
    dateCardImage: {
      height: 28,
      width: 28,
      marginRight: 10,
    },
    dateCardImageImg: {
      height: 28,
      width: 28,
    },
    dateCardText: {
      fontSize: 11,
      fontWeight: '400',
      lineHeight: 15,
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    dateCardRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderColor: '#eeeeee',
      borderBottomWidth: 1,
      marginBottom: 15,
    },
    dateCardTo: {
      textTransform: 'uppercase',
      fontSize: 12,
      lineHeight: 15,
      fontWeight: '400',
      marginBottom: 15,
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
  });
};

export default styles;
