import {Dimensions, StyleSheet} from 'react-native';

const styles = (theme: any) => {
  return StyleSheet.create({
    mainContainer: {
      backgroundColor: theme.colors.primaryBg,
      flex: 1,
      width: Dimensions.get('window').width,
      alignItems: 'center',
      position: 'relative',
      // paddingBottom: 20,
    },
    innerContainer: {
      paddingHorizontal: 21,
      flex: 1,
    },
    flex1: {
      flex: 1,
    },
    filterRowContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: Dimensions.get('window').width * 0.9,
      marginTop: 15,
      paddingBottom: 10,
    },
    filterItem: {
      width: '48%',
      height: 35,
      borderColor: theme.colors.secondaryText,
      borderWidth: 1,
      borderRadius: 4,
      justifyContent: 'center',
      alignItems: 'center',
    },
    filterItemText: {
      textAlign: 'center',
      fontFamily: theme.fonts.poppingsNormal,
      fontWeight: '400',
      fontSize: 13,
      color: theme.colors.drawerText,
    },
    statsCard: {
      borderColor: theme.colors.primaryBorder,
      borderWidth: 1,
      borderRadius: 8,
      width: Dimensions.get('window').width * 0.9,
      minHeight: 100,
      backgroundColor: theme.colors.lightGrayBg,
      shadowColor: theme.colors.primaryShadow,
      shadowOffset: {width: 2, height: 1},
      shadowOpacity: 0.3,
      shadowRadius: 5,
      elevation: 4,
      marginBottom: 20,
    },
    statsCardHeader: {
      width: Dimensions.get('window').width * 0.895,
      height: 45,
      paddingHorizontal: 15,
      justifyContent: 'center',
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
    },
    statsCardHeading: {
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 15,
      fontWeight: '500',
      color: theme.colors.lightGrayBg,
    },
    statsCardInnerContainer: {paddingHorizontal: 14, marginBottom: 5},
    statsCardTabContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      marginTop: 5,
    },
    statsCardTab: {
      width: '50%',
      height: 30,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.primaryBorder,
      justifyContent: 'center',
    },
    statsCardTabSelected: {
      borderBottomColor: theme.colors.lightBlueBg,
      borderBottomWidth: 2,
    },
    statsCardTabText: {
      textAlign: 'center',
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 12,
      fontWeight: '500',
      color: theme.colors.secondaryText,
    },
    blueText: {
      color: theme.colors.lightBlueBg,
      fontWeight: '500',
    },
    tableWrapper: {
      marginTop: 12,
      marginBottom: 20,
      borderRadius: 4,
      overflow: 'hidden',
    },
    tableBorderStyle: {borderWidth: 2, borderColor: theme.colors.primaryBorder},
    tableHeaderRowStyle: {
      height: 40,
      backgroundColor: '#009BDB',
    },
    tableHeaderTextStyle: {
      marginLeft: 6,
      marginVertical: 6,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 12,
      fontWeight: '500',
      color: theme.colors.primaryBg,
    },
    tableFooterRowStyle: {
      height: 40,
      backgroundColor: theme.colors.primaryBorder,
    },
    tableFooterTextStyle: {
      marginLeft: 6,
      marginVertical: 6,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 11,
      fontWeight: '600',
      color: theme.colors.drawerText,
    },
    tableBodyTextStyle: {
      marginLeft: 6,
      marginVertical: 6,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 11,
      fontWeight: '500',
      color: theme.colors.drawerText,
    },
    wagerActivityData: {
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.primaryBorder,
    },
    pb0: {
      paddingBottom: 0,
    },
    wagerActivityHeadingRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    innerHeadingText: {
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 18,
      fontWeight: '500',
      color: theme.colors.drawerText,
    },
    wagerTextWrapper: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 16,
    },
    wagerTextFirst: {
      marginBottom: 10,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 14,
      fontWeight: '500',
      color: theme.colors.drawerText,
    },
    wagerTextSecond: {
      marginBottom: 8,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 12,
      fontWeight: '500',
      color: theme.colors.secondaryText,
    },
    lightGreenColor: {
      color: theme.colors.onlineGreen,
    },

    modalInnerContainer: {
      maxHeight: '70%',
      minHeight: 200,
      marginTop: 'auto',
      backgroundColor: theme.colors.primaryText,
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
      padding: 20,
    },
    handleBar: {
      backgroundColor: theme.colors.barColor,
      width: 80,
      height: 8,
      borderRadius: 30,
      alignSelf: 'center',
    },
    textWrapper: {marginTop: 23},
    modalText: {
      fontSize: 16,
      marginBottom: 15,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.secondaryText,
      fontWeight: '400',
    },
    filterItemCircle: {
      height: 16,
      width: 16,
      borderColor: theme.colors.primaryBorder,
      borderWidth: 2,
      borderRadius: 50,
      justifyContent: 'center',
      alignItems: 'center',
    },
    filterItemInnerCircle: {
      backgroundColor: theme.colors.lightBlueText,
      height: 8,
      width: 8,
      borderRadius: 50,
    },
    lightBlueBorder: {
      borderColor: theme.colors.lightBlueText,
    },
    filterItemModal: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    filterItemWrapper: {
      shadowColor: theme.colors.primaryBorder,
      shadowOffset: {width: 0, height: 3},
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 4,
      marginBottom: 24,
    },
    filterItemLabel: {
      color: theme.colors.drawerText,
      fontWeight: '500',
      fontSize: 14,
      fontFamily: theme.fonts.poppingsNormal,
    },
    modalHeadingText: {
      color: '#009BDB',
      fontWeight: '500',
      fontSize: 15,
      fontFamily: theme.fonts.poppingsNormal,
    },
    separator: {
      height: 2,
      width: '100%',
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.primaryBorder,
      marginTop: 19,
      marginBottom: 15,
    },
    floatingBtn: {
      position: 'absolute',
      bottom: 20,
      right: 20,
    },
    floatingBtnGradient: {
      alignItems: 'center',
      borderRadius: 50,
      width: 45,
      height: 45,
      justifyContent: 'center',
    },
  });
};

export default styles;
