import {Dimensions, StyleSheet} from 'react-native';

const styles = (theme: any) => {
  return StyleSheet.create({
    primaryButton: {
      padding: 0,
      width: '100%',
      height: 45,
      flex: 1,
    },
    primaryButtonGradient: {
      height: 45,
      padding: 0,
      borderRadius: 4,
      justifyContent: 'center',
      width: '100%',
    },
    secondaryButtonStyle: {
      height: 45,
      backgroundColor: '#00316B',
      borderRadius: 4,
      padding: 9,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    secondaryButtonTextStyle: {
      textAlign: 'center',
      fontWeight: '500',
      fontSize: 14,
      padding: 0,
      lineHeight: 18,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryText,
    },
    btnTextStyle: {
      textAlign: 'center',
      fontWeight: '500',
      fontSize: 14,
      padding: 0,
      lineHeight: 20,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryText,
    },
    tribeCardPage: {
      padding: 15,
      flex: 1,
      width: '100%',
    },
    width100: {width: '100%'},
    tribeFullCard: {
      borderRadius: 8,
      borderWidth: 1,
      shadowOffset: {width: 2, height: 6},
      shadowRadius: 6,
      shadowOpacity: 0.2,
      elevation: 5,
      width: '100%',
      backgroundColor: '#ffffff',
      borderColor: '#eeeeee',
      marginBottom: 40,
    },
    tribeCard: {
      borderTopRightRadius: 8,
      borderTopLeftRadius: 8,
      padding: 14,
      marginBottom: 15,
      width: '100%',
      backgroundColor: theme.colors.lightGrayBg,
      flex: 1,
    },
    tribeCardHeader: {
      flexDirection: 'row',
      marginBottom: 15,
    },
    tribeInfoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
    },
    tribeInfoText: {
      fontSize: 11,
      lineHeight: 20,
      fontWeight: '400',
    },
    tribeInfoTextSmall: {
      fontSize: 11,
      lineHeight: 20,
      fontWeight: '400',
      color: '#009BDB',
      fontStyle: 'italic',
    },
    tribeInfoTextBlue: {
      fontSize: 11,
      lineHeight: 20,
      fontWeight: '400',
      color: '#009BDB',
    },
    tribeText: {
      color: '#808080',
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 12,
      lineHeight: 20,
      fontWeight: '400',
      paddingHorizontal: 15,
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    tribeText11: {
      color: '#808080',
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 11,
      lineHeight: 20,
      fontWeight: '400',
      paddingHorizontal: 15,
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    tribePrices: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    tribePrice: {
      backgroundColor: '#E3E3E3',
      height: 35,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 4,
      width: '48%',
      display: 'flex',
      marginBottom: 15,
    },
    tribePriceText: {
      fontFamily: theme.fonts.poppingsSemiBold,
      fontSize: 12,
      lineHeight: 24,
      fontWeight: '500',
    },
    tribeCardBox: {
      flexDirection: 'row',
    },
    tribeHImage: {
      backgroundColor: '#ffffff',
      height: 50,
      width: 50,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
      borderColor: '#eeeeee',
      borderWidth: 1,
    },
    tribeLogo: {
      width: 45,
      height: 45,
    },
    tribeDetail1: {
      justifyContent: 'center',
    },
    textDark: {
      color: theme.colors.drawerText,
    },
    tribeTitle: {
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500',
      paddingHorizontal: 15,
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    tribeStatus: {
      backgroundColor: '#D6EDBC',
      borderRadius: 4,
      height: 20,
      width: 50,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'flex-start',
      flexDirection: 'row',
    },
    tribeStatusDanger: {
      backgroundColor: '#ff0000',
      borderRadius: 4,
      height: 20,
      width: 50,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'flex-start',
      flexDirection: 'row',
    },
    tribeStatusClosed: {
      backgroundColor: '#e9e9e9',
      borderRadius: 4,
      height: 20,
      width: 50,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'flex-start',
      flexDirection: 'row',
    },
    tribeStatusText: {
      fontSize: 12,
      lineHeight: 20,
      fontWeight: '500',
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    dateCard: {
      flexDirection: 'row',
      marginBottom: 15,
    },
    dateCardImage: {
      height: 28,
      width: 28,
      marginRight: 10,
    },
    dateCardImageImg: {
      height: 28,
      width: 28,
    },
    dateCardText: {
      fontSize: 11,
      fontWeight: '400',
      lineHeight: 15,
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    dateCardRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderColor: '#eeeeee',
      borderBottomWidth: 1,
      marginBottom: 15,
    },
    dateCardTo: {
      textTransform: 'uppercase',
      fontSize: 12,
      lineHeight: 15,
      fontWeight: '400',
      marginBottom: 15,
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    privateTribeWr: {
      width: '100%',
      padding: 15,
    },
    privateTribeHeading: {
      fontSize: 15,
      marginBottom: 15,
      lineHeight: 15,
      fontWeight: '400',
    },
    privateTribe: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      flex: 1,
    },

    privateTribeView: {
      width: '50%',
      marginBottom: 15,
      display: 'flex',
    },
    inputStyle: {
      fontSize: 14,
      fontWeight: '400',
      width: '100%',
      height: '100%',
      borderColor: theme.colors.primaryBorder,
      borderWidth: 1,
      borderStyle: 'solid',
      color: theme.colors.blackText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    inputStyleWr: {
      width: '100%',
      height: '100%',
    },
    inlineStyleWr: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      // alignItems: 'center',
      width: '100%',
    },
    inlineSwitchRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      alignItems: 'center',
      padding: 15,
    },
    tribePageStyle: {
      flexDirection: 'column',
      flex: 1,
      height: '100%',
    },
    publicSearchWr: {
      backgroundColor: '#E3E3E3',
      paddingHorizontal: 15,
      paddingVertical: 6,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      height: 60,
    },
    publicSearchView: {
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      flex: 1,
    },
    publicSearchField: {
      alignItems: 'flex-start',
      flex: 2,
    },
    flexCenterRight: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      height: '100%',
    },
    teamLogo: {
      width: 60,
      height: 60,
      borderRadius: 25,
      backgroundColor: theme.colors.lightGrayBg,
    },
    secondaryButtonSmStyle: {
      height: 35,
      backgroundColor: '#E3E3E3',
      borderRadius: 4,
      padding: 9,
      width: '100%',
    },
    secondaryButtonTextSmStyle: {
      textAlign: 'center',
      fontWeight: '500',
      fontSize: 14,
      padding: 0,
      lineHeight: 18,
      fontFamily: theme.fonts.poppingsNormal,
      color: '#0C0712',
    },
    createTribeBtn: {
      flexDirection: 'row',
      paddingHorizontal: 15,
      justifyContent: 'space-between',
      width: '100%',
    },
    tableHeaderGradientStyle: {
      height: 50,
      justifyContent: 'space-between',
      width: '100%',
      flexDirection: 'row',
    },
    tabViewText: {
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryText,
      fontSize: 14,
      fontWeight: '500',
      padding: 15,
    },
    tabViewTextActive: {
      fontFamily: theme.fonts.poppingsNormal,
      color: '#009BDB',
      fontSize: 14,
      fontWeight: '500',
      padding: 15,
    },
    contentPage: {
      padding: 15,
      flex: 1,
      width: '100%',
    },
    contentPageHeading: {
      fontSize: 16,
      lineHeight: 20,
      marginBottom: 15,
      marginTop: 10,
      fontWeight: '500',
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    contentPageSubHeading: {
      fontSize: 14,
      lineHeight: 18,
      marginBottom: 10,
      marginTop: 10,
      fontWeight: '500',
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    contentPageText: {
      fontSize: 14,
      lineHeight: 22,
      marginBottom: 15,
      fontWeight: '500',
      color: '#808080',
      fontFamily: theme.fonts.poppingsNormal,
    },
    contentPageActions: {
      flexDirection: 'row',
      paddingHorizontal: 15,
      justifyContent: 'space-between',
      width: '100%',
    },

    contentPageActionsView: {
      width: '48%',
      marginBottom: 15,
      display: 'flex',
    },
    tribeMembers: {
      width: '100%',
      flexDirection: 'column',
      paddingHorizontal: 15,
    },
    tribeMember: {
      width: '100%',
      flexDirection: 'row',
      paddingVertical: 15,
      borderBottomColor: '#efefef',
      borderBottomWidth: 1,
    },
    tribeMemberLogoWr: {
      width: 45,
      height: 45,
      borderRadius: 8,
      marginRight: 15,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#efefef',
    },
    tribeMemberLogo: {
      width: 35,
      height: 35,
    },
    tribeMemberInfo: {
      width: '82%',
    },
    tribeMemberTitle: {
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500',
      alignItems: 'center',
    },
    lineViewSelect: {
      width: '102%',
      position: 'relative',
      marginLeft: 15,
      marginBottom: 15,
    },
    tribeWagerPage: {
      width: '100%',
      paddingVertical: 15,
    },
    mainContainer: {
      backgroundColor: theme.colors.primaryBg,
      flex: 1,
      width: Dimensions.get('window').width,
      alignItems: 'center',
      position: 'relative',
      paddingBottom: 20,
    },
    innerContainer: {
      paddingHorizontal: 21,
      flex: 1,
    },
    flex1: {
      flex: 1,
    },
    filterRowContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: Dimensions.get('window').width * 0.9,
      paddingBottom: 10,
    },
    filterItem: {
      width: '100%',
      height: 35,
      borderColor: theme.colors.secondaryText,
      borderWidth: 1,
      borderRadius: 4,
      justifyContent: 'center',
      alignItems: 'center',
    },
    filterItemText: {
      textAlign: 'center',
      fontFamily: theme.fonts.poppingsNormal,
      fontWeight: '400',
      fontSize: 13,
      color: theme.colors.drawerText,
    },
    statsCard: {
      borderColor: theme.colors.primaryBorder,
      borderWidth: 1,
      borderRadius: 8,
      width: Dimensions.get('window').width * 0.9,
      minHeight: 100,
      backgroundColor: theme.colors.lightGrayBg,
      shadowColor: theme.colors.primaryShadow,
      shadowOffset: {width: 2, height: 1},
      shadowOpacity: 0.3,
      shadowRadius: 5,
      elevation: 4,
      marginBottom: 20,
    },
    statsCardHeader: {
      width: Dimensions.get('window').width * 0.895,
      height: 45,
      paddingHorizontal: 15,
      justifyContent: 'center',
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
    },
    statsCardHeading: {
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 15,
      fontWeight: '500',
      color: theme.colors.lightGrayBg,
    },
    statsCardInnerContainer: {paddingHorizontal: 14, marginBottom: 5},
    statsCardTabContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      marginTop: 5,
    },
    statsCardTab: {
      width: '50%',
      height: 30,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.primaryBorder,
      justifyContent: 'center',
    },
    statsCardTabSelected: {
      borderBottomColor: theme.colors.lightBlueBg,
      borderBottomWidth: 2,
    },
    statsCardTabText: {
      textAlign: 'center',
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 12,
      fontWeight: '500',
      color: theme.colors.secondaryText,
    },
    blueText: {
      color: theme.colors.lightBlueBg,
      fontWeight: '500',
    },
    tableWrapper: {
      marginTop: 12,
      marginBottom: 20,
      borderRadius: 4,
      overflow: 'hidden',
    },
    tableBorderStyle: {borderWidth: 2, borderColor: theme.colors.primaryBorder},
    tableHeaderRowStyle: {
      height: 40,
      backgroundColor: '#009BDB',
    },
    tableHeaderTextStyle: {
      marginLeft: 6,
      marginVertical: 6,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 12,
      fontWeight: '500',
      color: theme.colors.primaryBg,
    },
    tableFooterRowStyle: {
      height: 40,
      backgroundColor: theme.colors.primaryBorder,
    },
    tableFooterTextStyle: {
      marginLeft: 6,
      marginVertical: 6,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 11,
      fontWeight: '600',
      color: theme.colors.drawerText,
    },
    tableBodyTextStyle: {
      marginLeft: 6,
      marginVertical: 6,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 11,
      fontWeight: '500',
      color: theme.colors.drawerText,
    },
    wagerActivityData: {
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.primaryBorder,
    },
    pb0: {
      paddingBottom: 0,
    },
    wagerActivityHeadingRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    innerHeadingText: {
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 18,
      fontWeight: '500',
      color: theme.colors.drawerText,
    },
    wagerTextWrapper: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 16,
    },
    wagerTextFirst: {
      marginBottom: 10,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 14,
      fontWeight: '500',
      color: theme.colors.drawerText,
    },
    wagerTextSecond: {
      marginBottom: 8,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 12,
      fontWeight: '500',
      color: theme.colors.secondaryText,
    },
    lightGreenColor: {
      color: theme.colors.onlineGreen,
    },

    modalInnerContainer: {
      maxHeight: '70%',
      minHeight: 200,
      marginTop: 'auto',
      backgroundColor: theme.colors.primaryText,
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
      padding: 20,
    },
    handleBar: {
      backgroundColor: theme.colors.barColor,
      width: 80,
      height: 8,
      borderRadius: 30,
      alignSelf: 'center',
    },
    textWrapper: {marginTop: 23},
    modalText: {
      fontSize: 16,
      marginBottom: 15,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.secondaryText,
      fontWeight: '400',
    },
    filterItemCircle: {
      height: 16,
      width: 16,
      borderColor: theme.colors.primaryBorder,
      borderWidth: 2,
      borderRadius: 50,
      justifyContent: 'center',
      alignItems: 'center',
    },
    filterItemInnerCircle: {
      backgroundColor: theme.colors.lightBlueText,
      height: 8,
      width: 8,
      borderRadius: 50,
    },
    lightBlueBorder: {
      borderColor: theme.colors.lightBlueText,
    },
    filterItemModal: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    filterItemWrapper: {
      shadowColor: theme.colors.primaryBorder,
      shadowOffset: {width: 0, height: 3},
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 4,
      marginBottom: 24,
    },
    filterItemLabel: {
      color: theme.colors.drawerText,
      fontWeight: '500',
      fontSize: 14,
      fontFamily: theme.fonts.poppingsNormal,
    },
    modalHeadingText: {
      color: '#009BDB',
      fontWeight: '500',
      fontSize: 15,
      fontFamily: theme.fonts.poppingsNormal,
    },
    separator: {
      height: 2,
      width: '100%',
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.primaryBorder,
      marginTop: 19,
      marginBottom: 15,
    },
    editIconWrapper: {
      backgroundColor: theme.colors.lightBlueBg,
      borderWidth: 1,
      borderColor: 'white',
      width: 20,
      height: 20,
      borderRadius: 50,
      position: 'absolute',
      justifyContent: 'center',
      alignItems: 'center',
      top: -8,
      right: -8,
    },
    memberCrownIcon: {
      backgroundColor: theme.colors.lightBlueBg,
      borderWidth: 1,
      borderColor: 'white',
      width: 20,
      height: 20,
      borderRadius: 50,
      position: 'absolute',
      justifyContent: 'center',
      alignItems: 'center',
      top: -8,
      left: -8,
    },
  });
};

export default styles;
