import {StyleSheet} from 'react-native';

const styles = (theme: any) => {
  return StyleSheet.create({
    primaryButton: {
      padding: 0,
      width: '100%',
      height: 45,
      flex: 1,
    },
    primaryButtonGradient: {
      height: 45,
      padding: 0,
      borderRadius: 4,
      justifyContent: 'center',
      width: '100%',
    },
    secondaryButtonStyle: {
      height: 45,
      backgroundColor: '#00316B',
      borderRadius: 4,
      padding: 9,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    secondaryButtonTextStyle: {
      textAlign: 'center',
      fontWeight: '500',
      fontSize: 14,
      padding: 0,
      lineHeight: 18,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryText,
    },
    btnTextStyle: {
      textAlign: 'center',
      fontWeight: '500',
      fontSize: 14,
      padding: 0,
      lineHeight: 20,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryText,
    },
    tribeCardPage: {
      padding: 15,
      flex: 1,
      // height: 450,
      // width: '100%',
    },
    tribeCard: {
      borderRadius: 8,
      padding: 14,
      marginBottom: 15,
      width: '100%',
      borderColor: '#eeeeee',
      borderWidth: 1,
      shadowColor: '#171717',
      shadowOffset: {width: -2, height: 4},
      shadowOpacity: 0.2,
      shadowRadius: 3,
      // elevation: 4,
    },
    tribePrices: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    tribePrice: {
      backgroundColor: '#E3E3E3',
      height: 35,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 4,
      width: '48%',
      display: 'flex',
      marginBottom: 15,
    },
    tribePriceText: {
      fontFamily: theme.fonts.poppingsSemiBold,
      fontSize: 12,
      lineHeight: 24,
      fontWeight: '500',
    },
    tribeCardBox: {
      flexDirection: 'row',
      width: '100%',
      height: 80,
      shadowColor: '#171717',
      shadowOffset: {width: -2, height: 4},
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 4,
    },
    tribeHImage: {
      backgroundColor: theme.colors.lightGrayBg,
      height: 65,
      width: 65,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
    },
    tribeTitle: {
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '500',
      paddingHorizontal: 15,
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    width50: {width: '50%'},
    tribeText: {
      color: '#808080',
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 12,
      lineHeight: 20,
      fontWeight: '400',
      paddingHorizontal: 15,
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    tribeText11: {
      color: '#808080',
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 11,
      lineHeight: 20,
      fontWeight: '400',
      paddingHorizontal: 15,
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    tribeStatus: {
      backgroundColor: '#D6EDBC',
      borderRadius: 4,
      height: 20,
      width: 50,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'flex-start',
      flexDirection: 'row',
    },
    tribeStatusDanger: {
      backgroundColor: '#ff0000',
      borderRadius: 4,
      height: 20,
      width: 50,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'flex-start',
      flexDirection: 'row',
    },
    tribeStatusClosed: {
      backgroundColor: '#e9e9e9',
      borderRadius: 4,
      height: 20,
      width: 50,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'flex-start',
      flexDirection: 'row',
    },
    tribeStatusText: {
      fontSize: 12,
      lineHeight: 20,
      fontWeight: '500',
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    dateCard: {
      flexDirection: 'row',
      marginBottom: 15,
    },
    dateCardImage: {
      height: 28,
      width: 28,
      marginRight: 10,
    },
    dateCardImageImg: {
      height: 28,
      width: 28,
    },
    dateCardText: {
      fontSize: 11,
      fontWeight: '400',
      lineHeight: 15,
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    dateCardRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderColor: '#eeeeee',
      borderBottomWidth: 1,
      marginBottom: 15,
    },
    dateCardTo: {
      textTransform: 'uppercase',
      fontSize: 12,
      lineHeight: 15,
      fontWeight: '400',
      marginBottom: 15,
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    privateTribeWr: {
      width: '100%',
      paddingHorizontal: 7,
      paddingVertical: 15,
      height: 105,
    },
    privateTribeHeading: {
      fontSize: 15,
      paddingHorizontal: 8,
      marginBottom: 15,
      lineHeight: 15,
      fontWeight: '400',
    },
    privateTribe: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      flex: 1,
      width: '100%',
      paddingHorizontal: 8,
    },
    privateTribeView: {
      width: '49%',
      marginBottom: 15,
      display: 'flex',
    },
    inputStyle: {
      fontSize: 14,
      fontWeight: '400',
      width: '100%',
      height: 45,
      paddingHorizontal: 10,
      borderColor: theme.colors.primaryBorder,
      borderWidth: 1,
      borderStyle: 'solid',
      color: theme.colors.blackText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    fileUploadStyle: {
      fontSize: 14,
      fontWeight: '400',
      width: '100%',
      height: 45,
      paddingHorizontal: 10,
      borderColor: theme.colors.primaryBorder,
      borderWidth: 1,
      borderStyle: 'solid',
      padding: 10,
      textAlign: 'right',
      fontFamily: theme.fonts.poppingsNormal,
    },
    inputStyleWr: {
      width: '100%',
      height: '100%',
    },
    inlineStyleWr: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    tribePageStyle: {
      justifyContent: 'center',
      alignItems: 'center',
      height: '85%',
      backgroundColor: theme.colors.primaryText,
    },
    publicSearchWr: {
      backgroundColor: '#E3E3E3',
      paddingHorizontal: 15,
      paddingVertical: 6,
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      justifyContent: 'center',
      height: 60,
    },
    publicSearchView: {
      alignItems: 'flex-start',
      flex: 1,
    },
    publicSearchField: {
      alignItems: 'flex-end',
      flex: 1,
    },
    flexCenterRight: {
      // flex: 1,
      width: '30%',
      justifyContent: 'center',
      alignItems: 'center',
      height: '100%',
    },
    teamLogo: {
      width: 60,
      height: 60,
      borderRadius: 25,
      backgroundColor: theme.colors.lightGrayBg,
    },
    secondaryButtonSmStyle: {
      height: 35,
      backgroundColor: '#E3E3E3',
      borderRadius: 4,
      padding: 9,
      width: '100%',
    },
    secondaryButtonTextSmStyle: {
      textAlign: 'center',
      fontWeight: '500',
      fontSize: 14,
      padding: 0,
      lineHeight: 18,
      fontFamily: theme.fonts.poppingsNormal,
      color: '#0C0712',
    },
    createTribeBtn: {
      flexDirection: 'row',
      padding: 15,
      justifyContent: 'space-between',
      width: '100%',
      alignSelf: 'flex-end',
    },
    modalContentWrapper: {
      flexDirection: 'row',
      marginTop: 20,
      justifyContent: 'space-between',
      width: '100%',
      paddingHorizontal: 20,
    },
    thumbStyle: {
      backgroundColor: 'red',
      height: 13,
      width: 13,
      borderRadius: 50,
    },
    blueBg: {
      backgroundColor: theme.colors.lightBlueBg,
    },
    modalChildren: {
      paddingBottom: 20,
      alignItems: 'center',
    },
    modalFooterBtnWrapper: {
      width: '70%',
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      flexDirection: 'row',
      marginTop: 23,
    },
    modalGradientBtn: {
      paddingVertical: 14,
      borderRadius: 4,
      justifyContent: 'center',
    },
    w40: {
      width: '40%',
    },
    w45: {
      width: '45%',
    },
    ph15: {
      paddingHorizontal: 15,
    },
    ml15: {
      marginLeft: 15,
    },
  });
};

export default styles;
