import {Dimensions, StyleSheet} from 'react-native';

const styles = (theme: any) => {
  return StyleSheet.create({
    gradientStyle: {
      width: Dimensions.get('window').width,
      height: 60,
      paddingHorizontal: 20,
      justifyContent: 'center',
    },
    gradientinnerWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    teamLogo: {
      height: 40,
      width: 40,
      borderRadius: 50,
    },
    teamName: {
      color: theme.colors.primaryText,
      fontWeight: '600',
      fontSize: 18,
      fontFamily: theme.fonts.poppingsNormal,
      marginLeft: 10,
    },
    btnWrapper: {flexDirection: 'row', alignItems: 'center'},
    btnStyle: {width: 70},
    secondaryButtonStyle: {
      height: 35,
      backgroundColor: '#808080',
      borderRadius: 4,
      padding: 9,
      width: 110,
    },
    secondaryButtonTextStyle: {
      textAlign: 'center',
      fontWeight: '500',
      fontSize: 14,
      padding: 0,
      lineHeight: 18,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryText,
    },
    btnGradientStyle: {
      borderRadius: 4,
      height: 30,
      justifyContent: 'center',
    },
    primaryButton: {
      padding: 0,
      width: 110,
      height: 35,
    },
    primaryButtonGradient: {
      height: 35,
      padding: 0,
      borderRadius: 4,
      justifyContent: 'center',
    },
    btnTextStyle: {
      textAlign: 'center',
      fontWeight: '500',
      fontSize: 14,
      padding: 0,
      lineHeight: 20,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryText,
    },
    lineDropdownWr: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
    },
    lineViewLabelText: {
      fontFamily: theme.fonts.poppingsNormal,
      fontWeight: '400',
      fontSize: 13,
      color: theme.colors.drawerText,
      marginRight: 5,
    },
    lineViewSelect: {
      width: '85%',
      position: 'relative',
      right: -20,
    },
    separator: {
      borderBottomColor: theme.colors.primaryBorder,
      borderBottomWidth: 2,
      width: '90%',
      marginTop: 20,
      marginBottom: 10,
      alignSelf: 'center',
    },
    dropdownWrapperStyle: {
      flexDirection: 'row',
      padding: 15,
    },
    flexRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    w100: {
      width: '100%',
    },
    w50: {
      width: '50%',
    },
    dropdownLabelWrapper: {
      width: '100%',
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    dropdownButtonStyle: {
      backgroundColor: theme.colors.primaryText,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.colors.primaryBorder,
      width: '50%',
      height: 40,
    },
    dropdownOpened: {
      borderTopRightRadius: 8,
      borderTopLeftRadius: 8,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
    },
    dropdownButtonTextStyle: {
      textAlign: 'left',
      fontFamily: theme.fonts.poppingsNormal,
      fontWeight: '400',
      fontSize: 12,
      color: theme.colors.secondaryText,
    },
    tableHeaderGradientStyle: {
      width: Dimensions.get('window').width,
      height: 50,
      // paddingHorizontal: 15,
      justifyContent: 'center',
    },
    tabViewText: {
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryText,
      fontSize: 14,
      fontWeight: '500',
      padding: 15,
    },
    tabViewTextActive: {
      fontFamily: theme.fonts.poppingsNormal,
      color: '#009BDB',
      fontSize: 14,
      fontWeight: '500',
      padding: 15,
    },
    grayTabWr: {
      width: Dimensions.get('window').width,
      height: 45,
      backgroundColor: '#E3E3E3',
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 15,
    },
    grayTabViewText: {
      fontFamily: theme.fonts.poppingsNormal,
      color: '#0C0712',
      fontSize: 14,
      fontWeight: '400',
      padding: 12,
    },
    grayTabViewTextActive: {
      fontFamily: theme.fonts.poppingsNormal,
      color: '#009BDB',
      fontSize: 15,
      fontWeight: '400',
      padding: 12,
      borderBottomColor: '#009BDB',
      borderBottomWidth: 2,
    },
    swipeableTabsStyle: {
      display: 'flex',
    },
    WrMatchDetailsView: {
      padding: 20,
      width: '100%',
      paddingTop: 25,
    },
    WrMatchGrayView: {
      padding: 20,
      width: '100%',
      paddingTop: 25,
      backgroundColor: theme.colors.lightGrayBg,
    },
    WrMGVCards: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    WrMGVButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingLeft: 20,
      marginBottom: 11,
    },
    WrMGVScore: {
      paddingLeft: 20,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    headingStyle1: {
      fontStyle: 'normal',
      fontWeight: '500',
      fontSize: 20,
      lineHeight: 20,
      color: '#0C0712',
    },
    headingStyle2: {
      fontStyle: 'normal',
      fontWeight: '500',
      fontSize: 17,
      lineHeight: 20,
      color: '#0C0712',
    },
    subHeadingStyle1: {
      fontStyle: 'normal',
      fontWeight: '500',
      fontSize: 12,
      lineHeight: 20,
      color: '#808080',
      marginBottom: 15,
    },
    subHeadingStyle13: {
      fontStyle: 'normal',
      fontWeight: '500',
      fontSize: 12,
      lineHeight: 20,
      color: '#808080',
      marginBottom: 15,
    },
    teamDetails: {
      padding: 0,
      flexDirection: 'row',
      marginBottom: 10,
    },
    betRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingLeft: 35,
    },
    betOutlineInput: {
      height: 30,
      borderColor: '#E3e3e3',
      borderWidth: 2,
      borderRadius: 4,
      color: '#808080',
      shadowColor: '#E3e3e3',
      fontSize: 14,
      width: 75,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    teamsCards: {
      width: '42%',
      margin: 0,
    },
    teamCard: {
      margin: 0,
      paddingLeft: 34,
      position: 'relative',
    },
    teamHeadingStyle1: {
      fontStyle: 'normal',
      fontWeight: '500',
      fontSize: 16,
      lineHeight: 24,
      color: '#0C0712',
    },
    teamHeadingStyle1Blue: {
      fontStyle: 'normal',
      fontWeight: '500',
      fontSize: 16,
      lineHeight: 24,
      color: '#00316B',
    },
    blackCardsWr: {
      width: '100%',
    },
    blackCardsRow: {
      flexDirection: 'row',
      width: '60%',
    },
    blackCard: {
      backgroundColor: '#0C0712',
      color: '#ffffff',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 4,
      margin: 5,
      padding: 10,
      flex: 1,
    },
    blackCardValue1: {
      color: '#ffffff',
      textAlign: 'center',
      marginBottom: 8,
    },
    blackCardValue2: {
      color: '#009BDB',
      textAlign: 'center',
    },
    teamAvatarIcon24: {
      width: 24,
      height: 24,
      borderRadius: 25,
      backgroundColor: theme.colors.lightGrayBg,
      position: 'absolute',
      left: 0,
    },
    ml10: {
      marginLeft: 10,
    },
    ph15: {
      paddingHorizontal: 15,
    },
    modalGradientBtn: {
      paddingVertical: 14,
      borderRadius: 4,
      justifyContent: 'center',
    },
    w40: {
      width: '40%',
    },
    w45: {
      width: '45%',
    },
    WrGlCCard: {
      padding: 20,
      width: '100%',
    },
    WrMGVTeamButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      // marginBottom: 11,
      width: '100%',
    },
    secondaryOutlineButtonStyle: {
      height: 35,
      borderColor: '#808080',
      borderWidth: 2,
      borderRadius: 4,
      width: '47%',
      marginLeft: '3%',
    },
    secondaryOutlineTextStyle: {
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: 14,
      height: 35,
      padding: 0,
      lineHeight: 24,
      fontFamily: theme.fonts.poppingsNormal,
      color: '#0C0712',
    },
    primaryOutlineButtonStyle: {
      height: 35,
      borderColor: '#009BDB',
      borderWidth: 2,
      borderRadius: 4,
      width: '47%',
      marginRight: '3%',
    },
    primaryOutlineTextStyle: {
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: 14,
      height: 35,
      padding: 0,
      lineHeight: 24,
      fontFamily: theme.fonts.poppingsNormal,
      color: '#0C0712',
    },
    tableContainer: {
      flex: 1,
      paddingHorizontal: 16,
      backgroundColor: '#fff',
      width: '100%',
      marginBottom: 40,
    },
    tableBorderStyle: {
      borderWidth: 1,
      width: '100%',
      borderColor: theme.colors.primaryBorder,
      borderTopLeftRadius: 5,
      borderTopRightRadius: 5,
      overflow: 'hidden',
    },
    tableHeaderRowStyle: {
      height: 40,
      backgroundColor: '#009BDB',
      borderTopLeftRadius: 5,
      borderTopRightRadius: 5,
    },
    tableHeaderTextStyle: {
      marginLeft: 13,
      marginVertical: 6,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 12,
      fontWeight: '500',
      color: theme.colors.primaryBg,
      alignItems: 'center',
    },
    tableFooterRowStyle: {
      height: 40,
      backgroundColor: theme.colors.primaryBorder,
    },
    tableFooterTextStyle: {
      marginLeft: 6,
      marginVertical: 6,
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 11,
      fontWeight: '600',
      color: theme.colors.drawerText,
    },
    tableBodyTextStyle: {
      margin: 6,
      marginLeft: 13,
      fontSize: 12,
      color: '#0C0712',
      height: 28,
      paddingVertical: 5,
    },
    head: {height: 40, backgroundColor: '#f1f8ff'},
    labelText: {
      fontFamily: theme.fonts.poppingsNormal,
      fontWeight: '400',
      fontSize: 13,
      color: theme.colors.drawerText,
      paddingBottom: 8,
    },
    sportsBookView: {width: '50%', padding: 10},
    mt50: {
      marginTop: 50,
    },
    floatingBtn: {
      position: 'absolute',
      bottom: 20,
      right: 20,
    },
    floatingBtnGradient: {
      alignItems: 'center',
      borderRadius: 50,
      width: 45,
      height: 45,
      justifyContent: 'center',
    },
  });
};

export default styles;
