import {Dimensions, Platform, StyleSheet} from 'react-native';

const styles = (theme: any) => {
  return StyleSheet.create({
    mainWrapper: {
      backgroundColor: 'white',
      paddingHorizontal: 20,
      width: Dimensions.get('window').width,
      paddingTop: 20,
      flex: 1,
    },
    flex1: {
      flex: 1,
    },
    flexRow: {flexDirection: 'row', alignItems: 'center'},
    justifyBetween: {justifyContent: 'space-between'},
    headingText: {
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 14,
      fontWeight: '500',
      marginRight: 14,
      color: theme.colors.blackText,
    },
    activeEngineNameText: {
      fontFamily: theme.fonts.poppingsNormal,
      fontSize: 13,
      fontWeight: '400',
      textAlign: 'center',
      flex: 1,
      borderColor: theme.colors.lightBlueBg,
      borderWidth: 1,
      borderRadius: 4,
      paddingVertical: 5,
      color: theme.colors.drawerText,
    },
    cardWrapper: {
      backgroundColor: theme.colors.lightGrayBg,
      borderRadius: 8,
      width: '100%',
      shadowColor: theme.colors.primaryShadow,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.4,
      shadowRadius: 5,
      marginTop: 20,
      paddingHorizontal: 15,
      paddingVertical: 18,
    },
    cardItemHeading: {
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.drawerText,
      fontSize: 15,
      fontWeight: '500',
    },
    cardSliderRow: {
      marginTop: 13,
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    h2: {
      height: 2,
    },
    bgBlue: {backgroundColor: theme.colors.lightBlueText},
    bgGrey: {backgroundColor: theme.colors.secondaryText},
    thumbStyle: {
      backgroundColor: 'red',
      height: 13,
      width: 13,
      borderRadius: 50,
    },
    percentTextInput: {
      borderTopLeftRadius: 4,
      borderBottomLeftRadius: 4,
      backgroundColor: '#fff',
      width: 40,
      height: 34,
      textAlign: 'center',
      paddingTop: 5,
      borderWidth: 1,
      borderColor: theme.colors.primaryBorder,
      fontSize: 14,
      lineHeight: 16,
      fontWeight: '400',
      color: theme.colors.secondaryText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    percentText: {
      borderRadius: 4,
      // backgroundColor: '#fff',
      height: Platform.OS === 'android' ? 34 : 28,
      textAlignVertical: 'center',
      textAlign: 'center',
      paddingBottom: 5,
      paddingHorizontal: 2,
      fontSize: 14,
      lineHeight: Platform.OS === 'android' ? 16 : 22,
      fontWeight: '400',
      color: theme.colors.secondaryText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    btnStyle: {
      borderRadius: 4,
      paddingHorizontal: 40,
      paddingVertical: 8,
      backgroundColor: theme.colors.secondaryText,
    },
    btnTextStyle: {
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryBg,
      fontSize: 12,
      fontWeight: '400',
      textAlign: 'center',
    },
    totalText: {
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.drawerText,
      fontSize: 16,
      fontWeight: '500',
    },

    w40: {width: '40%'},
    cardItemNameText: {
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.secondaryText,
      fontSize: 13,
      fontWeight: '400',
      marginLeft: 8,
      width: '85%',
    },

    footerSeparator: {
      borderTopWidth: 1,
      borderTopColor: theme.colors.secondaryText,
      width: '100%',
      opacity: 0.3,
      height: 1,
      marginVertical: 20,
    },
    modalFooterBtnWrapper: {
      width: '100%',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      flexDirection: 'row',
      marginTop: 23,
    },
    modalGradientBtn: {
      height: 35,
      borderRadius: 4,
      justifyContent: 'center',
    },
    w45: {
      width: '47%',
    },
    ph15: {
      paddingHorizontal: 15,
    },
    btnStyleReset: {
      borderRadius: 4,
      width: '47%',
      height: 35,
      backgroundColor: theme.colors.primaryBorder,
      justifyContent: 'center',
    },
    btnTextStyleSave: {
      fontFamily: theme.fonts.poppingsNormal,
      color: '#fff',
      fontSize: 14,
      fontWeight: '500',
      textAlign: 'center',
    },
    btnTextStyleReset: {
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.secondaryText,
      fontSize: 12,
      fontWeight: '400',
      textAlign: 'center',
    },
    infoText: {
      textAlign: 'center',
      color: theme.colors.secondaryText,
      lineHeight: 20,
      fontSize: 13,
      marginTop: 20,
      marginBottom: 20,
    },
    floatingBtn: {
      position: 'absolute',
      bottom: 20,
      right: 20,
    },
    floatingBtnGradient: {
      alignItems: 'center',
      borderRadius: 50,
      width: 45,
      height: 45,
      justifyContent: 'center',
    },
  });
};

export default styles;
