export const headingJson: any = {
  attempts: 'Attempts',
  comp_pct: 'Comp Pct',
  completions: 'Completions',
  interceptions: 'Completions',
  pass_td: 'Pass Td',
  pass_yards: 'Pass Yards',
  pass_ypa: 'Pass Ypa',
  rating: 'Rating',
  sacks: 'Sacks',
  int: 'INT',
  tackles: 'Tackles',
  player: 'Player',
  rush_yards: 'Rush Yards',
  rush_ypa: 'Rush Ypa',
  rush_td: 'Rush Td',
  rec_yards: 'Rec Yards',
  rec_ypc: 'Rec Ypc',
  rec_td: 'Rec Td',
  fumbles_forced: 'Fumbles Forced',
  fumbles_recovered: 'Fumbles Recovered',
  FG_pct: 'FG Pct',
  avg_yds: 'Avg Yds',
  XP_pct: 'XP Pct',
  GP: 'GP',
  MIN: 'MIN',
  PTS: 'PTS',
  FGM: 'FGM',
  FGA: 'FGA',
  'FG%': 'FG%',
  '3PM': '3PM',
  '3PA': '3PA',
  '3P%': '3P%',
  FTM: 'FTM',
  FTA: 'FTA',
  'FT%': 'FT%',
  OREB: 'OREB',
  DREB: 'DREB',
  REB: 'REB',
  AST: 'AST',
  STL: 'STL',
  BLK: 'BLK',
  TO: 'TO',
  DD2: 'DD2',
  TD3: 'TD3',
  EFF: 'EFF',
  '+/-': '+/-',
};
