import {Dimensions, StyleSheet} from 'react-native';

const styles = (theme: any) => {
  return StyleSheet.create({
    flex1: {
      flex: 1,
    },
    postBtnWrapper: {
      position: 'absolute',
      right: 20,
      bottom: 14,
      backgroundColor: 'rgba(128, 128, 128, 0.3)',
      width: 70,
      height: 30,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 5,
    },
    activePostBtn: {
      position: 'absolute',
      right: 20,
      bottom: 14,
      backgroundColor: theme.colors.secondaryText,
      width: 70,
      height: 30,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 5,
    },
    postBtnText: {
      color: theme.colors.primaryText,
      fontFamily: theme.fonts.poppingsNormal,
      fontWeight: '500',
    },
    userInfoRow: {
      flexDirection: 'row',
      width: Dimensions.get('window').width * 0.9,
      alignItems: 'center',
      marginTop: 20,
    },
    avatar: {
      height: 51,
      width: 51,
      borderRadius: 50,
    },
    username: {
      marginLeft: 14,
    },
    userView: {
      width: '85%',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    titleText: {
      fontSize: 16,
      color: theme.colors.drawerText,
      fontWeight: '500',
      fontFamily: theme.fonts.poppingsNormal,
    },
    nameText: {
      fontSize: 12,
      color: theme.colors.secondaryText,
      fontWeight: '400',
      fontFamily: theme.fonts.poppingsNormal,
    },
    dropdownWrapperStyle: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginLeft: 14,
      alignSelf: 'center',
      marginTop: 10,
    },
    dropdownShadowWrapper: {
      shadowColor: theme.colors.primaryShadow,
      shadowOffset: {width: 0, height: 3},
      shadowOpacity: 0.2,
      shadowRadius: 5,
      elevation: 4,
      marginRight: 10,
    },
    dropdownButtonStyle: {
      backgroundColor: 'white',
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.primaryBorder,
      width: 120,
    },
    dropdownButtonTextStyle: {
      textAlign: 'left',
      fontFamily: theme.fonts.poppingsNormal,
      fontWeight: '400',
      fontSize: 12,
      color: theme.colors.secondaryText,
    },
    footerWrapper: {
      borderTopColor: theme.colors.primaryBorder,
      borderTopWidth: 1,
      width: Dimensions.get('window').width,
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      paddingTop: 8,
      paddingBottom: 20,
    },
    linearGradiantBtn: {
      height: 35,
      width: 35,
      borderRadius: 50,
      justifyContent: 'center',
      alignItems: 'center',
    },
    inputWrapper: {
      width: '90%',
    },
    inputField: {
      fontWeight: '400',
      fontSize: 15,
      marginTop: 10,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.secondaryText,
      textAlignVertical: 'top',
      maxHeight: Dimensions.get('window').height * 0.3,
    },
    crossIcon: {
      position: 'absolute',
      top: 15,
      right: 5,
      padding: 5,
    },
    imageSize: {height: 200, width: '100%', marginTop: 10},
    modalView: {
      width: 210,
      height: 100,
      marginTop: -Dimensions.get('window').height / 1.8,
      marginLeft: Dimensions.get('window').width / 2.5,
      backgroundColor: '#F9F9F9',
      borderRadius: 5,
      borderWidth: 2,
      borderColor: '#E3E3E3',
      alignItems: 'flex-start',
      justifyContent: 'center',
      padding: 10,
    },
    flexRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    popupText: {
      fontWeight: '400',
      fontSize: 15,
      marginRight: 5,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.lightBlueText,
    },
    loaderView: {
      flex: 1,
      position: 'absolute',
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
  });
};

export default styles;
