import {StyleSheet, Dimensions, Platform} from 'react-native';

const styles = (theme: any) => {
  return StyleSheet.create({
    mainWrapper: {
      backgroundColor: 'white',
      flex: 1,
      paddingHorizontal: 20,
    },
    mainContainer: {
      height: '59%',
      width: '100%',
    },
    height65: {
      height: '65%',
    },
    filterContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 20,
    },
    filterHeadingText: {
      marginRight: 10,
      fontWeight: '500',
      fontSize: 14,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.blackText,
    },
    filterText: {
      borderWidth: 1,
      borderColor: theme.colors.secondaryText,
      borderRadius: 4,
      paddingHorizontal: 15,
      paddingVertical: 5,
      fontSize: 13,
      fontWeight: '400',
      marginRight: 12,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.drawerText,
    },
    blueBorder: {
      borderColor: theme.colors.lightBlueBg,
    },
    mv20: {marginVertical: 20},
    btnStyle: {
      borderRadius: 4,
      paddingHorizontal: 11,
      paddingVertical: 4,
      height: 28,
      backgroundColor: theme.colors.primaryBorder,
      justifyContent: 'center',
      width: 150,
      alignSelf: 'flex-end',
    },
    btnTextStyle: {
      color: theme.colors.secondaryText,
      fontSize: 12,
      fontWeight: '400',
      fontFamily: theme.fonts.poppingsNormal,
      textAlign: 'center',
    },
    amountInputContainer: {
      width: 50,
    },
    amountTextBg: {
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.secondaryText,
      height: 28,
      width: '100%',
      borderRadius: 0,
    },
    amountTextInput: {
      width: 50,
      textAlign: 'center',
      padding: 0,
    },
    amountTextBgDark: {
      fontWeight: '400',
      color: theme.colors.primaryBg,
      fontSize: 12,
      fontFamily: theme.fonts.poppingsNormal,
      backgroundColor: theme.colors.secondaryText,
      borderColor: theme.colors.primaryBorder,
      borderWidth: 1,
      borderRadius: 4,
      paddingHorizontal: 10,
      textAlign: 'center',
      paddingTop: Platform.select({ios: 2, android: 5}),
      overflow: 'hidden',
      alignSelf: 'flex-end',
      marginTop: 20,
    },
    labelText: {
      marginBottom: 4,
      fontWeight: '400',
      fontSize: 13,
      color: theme.colors.drawerText,
      fontFamily: theme.fonts.poppingsNormal,
    },
    flexRow: {flexDirection: 'row'},
    justifyBetween: {justifyContent: 'space-between'},
    dropdownStyle: {width: 130, height: 28, borderRadius: 4},
    dropdownStyleSmall: {width: 94, height: 28, borderRadius: 4},
    fw700: {fontWeight: '700'},
    footerWrapper: {
      width: Dimensions.get('window').width,
      minHeight: 50,
      alignItems: 'center',
      paddingBottom: 20,
    },
    footerSeparator: {
      borderTopWidth: 1,
      borderTopColor: theme.colors.secondaryText,
      width: Dimensions.get('window').width * 0.9,
      opacity: 0.1,
      height: 1,
      marginBottom: 17,
    },
    footerTextWrapper: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: Dimensions.get('window').width * 0.9,
      marginBottom: 10,
    },
    footerTextLeft: {
      fontSize: 18,
      fontWeight: '600',
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.drawerText,
    },
    footerTextRight: {
      fontSize: 18,
      fontWeight: '500',
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.secondaryText,
    },
    btnAddToTracker: {
      width: '85%',
      marginTop: 15,
    },
    btnGradient: {
      paddingVertical: 10,
      borderRadius: 8,
    },
    btnText: {
      textAlign: 'center',
      fontSize: 18,
      fontFamily: theme.fonts.poppingsNormal,
      color: theme.colors.primaryText,
    },
    noBetContainer: {
      width: '100%',
      height: 100,
      alignItems: 'center',
      justifyContent: 'center',
    },
    renderView: {
      width: '100%',
      height: 40,
      marginVertical: 8,
      paddingHorizontal: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    topOptionView: {
      width: '90%',
      paddingVertical: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    bookBalanceView: {height: '90%', padding: 10},
  });
};

export default styles;
